services:
  postgres:
    image: postgres
    container_name: bookhub-postgres-db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5480:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bookhub-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: bookhub-pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
      - "5051:443"
    networks:
      - bookhub-network

  mailhog:
    image: mailhog/mailhog
    container_name: bookhub-mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog:/var/lib/mailhog
    networks:
      - bookhub-network

networks:
  bookhub-network:

volumes:
  postgres:
  mailhog:
