openapi: 3.1.0
info:
  title: Book Hub - OpenAPI 3.1
  description: Book-Hub is an open-source platform designed for book lovers and libraries. It helps manage books, track reading progress, and facilitate seamless book sharing.  
  version: 1.0.0

servers:
  - url: https://bookhub-api.vercel.app/api/v1
    description: V1 API
  - url: https://bookhub-api.vercel.app/api/v2
    description: V2 API
tags:
  - name: Authentication
    description: Operations related to Authentication
  - name: Books
    description: Operations related to books
  - name: Users
    description: Operations related to users

paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: Returns a list of all books in the system.
      parameters:
        - name: limit
          in: query
          description: The number of books to return
          required: false
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          description: The page number
          required: false
          schema:
            type: integer
            default: 1